#!/Users/mike/.pyenv/versions/3.6.5/envs/feke/bin/python

# -*- coding: utf-8 -*-
import re
import sys
import os

if 'feke' not in sys.path:
    sys.path.append('/Users/mike/Documents/hexo_dir/feke_framework')
#os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'web.settings')
from feke.core.management import execute_from_command_line

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(execute_from_command_line())


# WSGIRequestHandler 的 handle 方法处理请求，application由self.server.get_app()传递
# WSGIServer 保留着wsgi application，当有请求时通过get_app()传递给 Handler
# WSGIServer 每次来请求之后创建新的handler,但是什么时候调用了handler的handle方法？？
# 上面的application 其实是WSGIHandler实例, 在WSGIRequestHandler的父类BaseHandler的run方法中对实例进行调用
